#!/bin/sh

[ -d /sys/kernel/config/usb_gadget/adb ] || exit 0

cd /sys/kernel/config/usb_gadget/adb

echo -n "" > UDC || true

umount /dev/usb-ffs/adb
rmdir /dev/usb-ffs/adb

rm configs/c.1/ffs.usb0

rmdir configs/c.1/strings/0x409
rmdir configs/c.1

rmdir functions/ffs.usb0
rmdir strings/0x409

cd ..
rmdir adb
